# Settings for logging into Tableau Online / Server
tableau_login:
  host: https://server-address.online.tableau.com  # https://<server_address>.online.tableau.com
  site: site_name  # <site> in https://<server_address>.online.tableau.com/#/site/<site>
  api_version: 3.16  # https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_whats_new.htm
  user: username
  password: password

# Settings for embedding connection credentials into Datasources
embed_connection:
  class_name: snowflake  # Connection type for embed credentials. e.g. snowflake or redshift
  server: https://some.url.com  # Connection Host (URL or IP Address)
  username: username
  password: password
  dbname: database_name
  schema: schema_name
  service: role_name  # (Optional) The role for the connection
  warehouse: warehouse_name
