# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: pr-automation
on: pull_request

jobs:
  pr-automation:
    uses: hoverinc/action-pr-automation/.github/workflows/pr-automation.yml@a0df467335de23b76f796a42822c9a88461f7192 # v1.4.1
    secrets: inherit
